import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
} from "@clerk/nextjs";
import Navbar from "@/app/(components)/Navbar";
import AppContextProvider from "./(components)/AppContext";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <div className="w-full h-full flex p-8 justify-evenly bg-primary">
            <SignedOut>
              <div className="w-full h-full flex items-center gap-5 justify-center">
                <SignInButton mode="modal">
                  <button className="signbtn">Sign In</button>
                </SignInButton>
                <SignUpButton mode="modal">
                  <button className="signbtn">Sign Up</button>
                </SignUpButton>
              </div>
            </SignedOut>
            <SignedIn>
              <div className="flex gap-5 w-full h-full flex-col sm:flex-row">
                <Navbar />
                <AppContextProvider>
                  <div
                    className="grayComp flex flex-col w-full wide"
                    // style={{ width: "100%" }}
                  >
                    {children}
                  </div>
                </AppContextProvider>
              </div>
            </SignedIn>
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
